name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@f2cdceb4c2843fddaa303dc5e33a1f9e3b234954 # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@15b5b41bb7d36796d89f4bf482b09529c53f3446 # v2.9.2
        with:
          file-coverage-mode: all
          comment-on: none

  build-actions:
    name: Build actions
    needs: check-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@f2cdceb4c2843fddaa303dc5e33a1f9e3b234954 # main
        with:
          persist-credentials: true

      - name: Build actions
        run: bun run build:actions

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'chore(actions): update build artifacts'
          file_pattern: filesize-diff/dist
