name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@5b6122e3a819a3be7b27fc961b7faafb3bf00e4d # v2.9.0
        with:
          file-coverage-mode: all
          comment-on: none

  build-actions:
    name: Build actions
    needs: check-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@main
        with:
          persist-credentials: true

      - name: Build actions
        run: bun run build:actions

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: 'chore(actions): update build artifacts'
          file_pattern: filesize-diff/dist
