name: Release

on:
  workflow_call:
    inputs:
      build:
        description: The command to build the project
        required: false
        type: string
        default: bun run build
      publish:
        description: Whether to publish the package
        required: false
        type: boolean
        default: false
      workflow-cleanup:
        description: 'The workflow where skipped runs on main branch should be cleaned up (ex: ci.yml)'
        required: false
        type: string
        default: ''

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@44f659c561819f2e977fcd23e201b4df25fbfe96 # main
        with:
          fetch-all: true

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build }}

      - name: Update npm
        run: npm install -g npm@latest
        if: ${{ inputs.publish }}

      - name: Publish
        run: npm publish --access public --tag ${{ contains(github.ref_name, 'beta') && 'beta' || 'latest' }}
        if: ${{ inputs.publish }}

      - name: Create release notes
        run: bunx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  workflow-cleanup:
    name: Workflow Cleanup
    runs-on: ubuntu-latest

    if: ${{ inputs.workflow-cleanup }}

    permissions:
      actions: write

    steps:
      - name: Cleanup skipped workflow runs on main branch
        run: gh run list -R $REPO --workflow ${{ inputs.workflow-cleanup }} --branch main --status skipped --json databaseId --jq '.[].databaseId' | xargs -rn 1 gh run delete -R $REPO
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
